[pytest]
markers =
    sanity: Run sanity tests
    ui: Run UI tests
    functional: Run functional tests
    negative: Run negative tests
    errors_handling: Run error handling tests
    integration: Run integration tests
    boundary: Run boundary tests
    smoke: Run smoke tests